language: python

python:
  - "2.7_with_system_site_packages"

install:
  - "sudo apt-get install python-pil python-reportlab"
  - "pip install -r requirements.txt"

before_script:
  - "cp itkufs/settings/local.py.template itkufs/settings/local.py"

script:
  - "python manage.py test"
